# Generated by Django 2.1.1 on 2018-09-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('user_passwd', models.CharField(max_length=32)),
                ('user_phone', models.IntegerField()),
                ('user_email', models.CharField(max_length=64, unique=True)),
                ('user_sex', models.BooleanField(default=1)),
                ('user_img', models.ImageField(upload_to='users')),
                ('user_is_admin', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'djblog_user',
            },
        ),
    ]
