# Generated by Django 2.1.1 on 2018-09-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180923_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
