# Generated by Django 2.1.1 on 2018-09-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180924_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_img',
            field=models.ImageField(null=True, upload_to='users'),
        ),
    ]
