# Generated by Django 2.1.1 on 2018-09-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180924_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_phone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
