# Generated by Django 2.1.1 on 2018-10-18 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='author',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='users.UserModel', verbose_name='作者'),
        ),
    ]
