# Generated by Django 2.1.3 on 2018-11-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (1, '草稿'), (2, '删除'), (3, '彻底删除')], default=0, verbose_name='状态'),
        ),
    ]
