# Generated by Django 2.1.1 on 2018-10-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181018_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostmodel',
            name='pub_time',
        ),
        migrations.AlterField(
            model_name='blogpostmodel',
            name='en_title',
            field=models.CharField(max_length=100, null=True, verbose_name='英文标题'),
        ),
    ]
