# Generated by Django 2.1.3 on 2018-11-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_swipers'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselmodel',
            name='img_url',
            field=models.TextField(default='/static/upload/carousels/django.png'),
        ),
    ]
