# Generated by Django 2.1.3 on 2018-12-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_carouselmodel_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodel',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
    ]
