# Generated by Django 2.1.3 on 2019-01-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpostmodel_comment_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='swipers',
            name='swiper_title',
            field=models.TextField(default='默认标题', max_length=100, null=True),
        ),
    ]
