# Generated by Django 2.1.3 on 2018-11-22 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('blog', '0003_swipers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.IntegerField(default=0)),
                ('comment_to_which_Comment', models.IntegerField(null=True)),
                ('comment_detail', models.TextField(max_length=200)),
                ('comment_time', models.DateTimeField(auto_now=True)),
                ('comment_zan_times', models.IntegerField(default=0)),
                ('comment_is_not_read', models.BooleanField(default=0)),
                ('comment_creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserModel')),
                ('comment_to_which_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPostModel')),
            ],
        ),
    ]
